### ISSUE TITLE
App crashes when loading play-style of user

### ISSUE THREAD

**Issue by Bgagger** [basstabs/NEForumMessenger#20]
The app crashes when opening the play-style of:
JulieNychols
The behavior is consistent.

**Comment by basstabs** [comment]
Fixed for next release. A side effect of emojis, external images would break the app since the current image getter attempts to load the src attribute from local storage, but they don't exist there. A quick fix has been added with a try-catch block, in the future it may be possible to attempt to load external images, but that is certainly a stretch feature.

Will wait to close the issue until the next release and the OP can verify that this is solved.

**Comment by Bgagger** [comment]
Confirmed to be working now.
